!/bin/bash
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_3/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_3/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_5/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_5/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_7/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_7/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_9/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_9/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_4/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_4/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_6/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_6/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ha_8/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ha_8/

python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/am_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/am_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/am_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/am_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/kh_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/kh_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/kh_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/kh_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ma_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ma_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ne_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ne_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_3/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_3/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_5/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_5/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_7/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_7/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_9/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_9/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_3/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_3/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_5/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_5/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_7/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_7/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/se_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/se_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/am_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/am_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/am_3/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/am_3/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/kh_1/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/kh_1/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ma_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ma_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/ma_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/ma_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_4/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_4/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_6/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_6/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pa_8/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pa_8/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_2/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_4/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_4/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/pu_6/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/pu_6/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/se_0/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/se_0/
python detect_maps.py --image_folder /home/omossad/scratch/Gaming-Dataset/selected_frames/fifa/se_2/ --out_folder /home/omossad/scratch/Gaming-Dataset/maps/fifa/se_2/
